// Generated by CoffeeScript 1.7.1
(function() {
  var ASSETS_PATH, CSS_LIBS, CUSTOM_COFFEE_PATH, CUSTOM_JADE_PATH, CUSTOM_STYLUS_PATH, JS_LIBS, env, fsExtra, getLibPaths, gulp, gulpCoffee, gulpConcat, gulpIf, gulpJade, gulpMinifyCss, gulpStylus, gulpUglify;

  gulp = require('gulp');

  gulpCoffee = require('gulp-coffee');

  gulpConcat = require('gulp-concat');

  gulpIf = require('gulp-if');

  gulpJade = require('gulp-jade');

  gulpMinifyCss = require('gulp-minify-css');

  gulpStylus = require('gulp-stylus');

  gulpUglify = require('gulp-uglify');

  fsExtra = require('fs-extra');

  env = require('./env');

  ASSETS_PATH = 'assets/';

  CUSTOM_COFFEE_PATH = ASSETS_PATH + 'scripts/**/*.coffee';

  CUSTOM_STYLUS_PATH = ASSETS_PATH + 'styles/**/*.styl';

  CUSTOM_JADE_PATH = ASSETS_PATH + 'views/**/*.jade';

  JS_LIBS = {
    "angular": {
      main: "angular.js",
      min: "angular.min.js"
    },
    "angular-resource": {
      main: "angular-resource.js",
      min: "angular-resource.min.js"
    },
    "angular-route": {
      main: "angular-route.js",
      min: "angular-route.min.js"
    },
    "jquery": {
      main: "dist/jquery.js",
      min: "jquery.min.js"
    },
    "bootstrap": {
      main: "dist/js/bootstrap.js",
      min: "dist/js/bootstrap.min.js"
    }
  };

  CSS_LIBS = {
    "bootstrap": {
      main: "dist/css/bootstrap.css",
      min: "dist/css/bootstrap.min.css"
    }
  };

  getLibPaths = function(libs) {
    return Object.keys(libs).map(function(libName) {
      return ASSETS_PATH + 'libs/' + libName + '/' + (env.compressed ? libs[libName].min : libs[libName].main);
    });
  };

  gulp.task('customCoffee', function() {
    return gulp.src(CUSTOM_COFFEE_PATH).pipe(gulpCoffee()).pipe(gulpIf(env.compressed, gulpUglify())).pipe(gulpConcat('custom.js')).pipe(gulp.dest(ASSETS_PATH + 'dist/js/'));
  });

  gulp.task('libJs', function() {
    return gulp.src(getLibPaths(JS_LIBS)).pipe(gulpConcat('libs.js')).pipe(gulp.dest(ASSETS_PATH + 'dist/js/'));
  });

  gulp.task('combineJs', ['customCoffee', 'libJs'], function() {
    return gulp.src([ASSETS_PATH + 'dist/js/{libs.js,custom.js}']).pipe(gulpConcat('all.js')).pipe(gulp.dest(ASSETS_PATH + 'dist/js/'));
  });

  gulp.task('customStylus', function() {
    return gulp.src(CUSTOM_STYLUS_PATH).pipe(gulpStylus()).pipe(gulpMinifyCss()).pipe(gulpConcat('custom.css')).pipe(gulp.dest(ASSETS_PATH + 'dist/css/'));
  });

  gulp.task('libCss', function() {
    return gulp.src(getLibPaths(CSS_LIBS)).pipe(gulpConcat('libs.css')).pipe(gulp.dest(ASSETS_PATH + 'dist/css/'));
  });

  gulp.task('combineCss', ['customStylus', 'libCss'], function() {
    return gulp.src(ASSETS_PATH + 'dist/css/{libs.css,custom.css}').pipe(gulpConcat('all.css')).pipe(gulp.dest(ASSETS_PATH + '/dist/css/'));
  });

  gulp.task('distributeBootstrapExtras', function() {
    return fsExtra.copy("" + ASSETS_PATH + "libs/bootstrap/dist/fonts", ASSETS_PATH + '/dist/fonts', function(err) {
      if (err) {
        return console.error(err);
      }
    });
  });

  gulp.task('customJade', function() {
    return gulp.src(CUSTOM_JADE_PATH).pipe(gulpJade()).pipe(gulp.dest(ASSETS_PATH + '/dist/html/'));
  });

  gulp.task('watch', function() {
    gulp.watch(CUSTOM_COFFEE_PATH, ['customCoffee', 'combineJs']);
    gulp.watch(CUSTOM_STYLUS_PATH, ['customStylus', 'combineCss']);
    return gulp.watch(CUSTOM_JADE_PATH, ['customJade']);
  });

  gulp.task('build', ['customCoffee', 'libJs', 'customStylus', 'libCss', 'combineJs', 'combineCss', 'distributeBootstrapExtras', 'customJade']);

  gulp.task('default', ['build', 'watch']);

}).call(this);

//# sourceMappingURL=gulpfile.map
