// Generated by CoffeeScript 1.7.1
(function() {
  var User, mongoose, userSchema;

  mongoose = require('mongoose');

  userSchema = null;

  User = (function() {
    function User() {}

    userSchema = new mongoose.Schema({
      fbId: {
        type: String,
        required: true,
        unique: true
      },
      name: {
        type: String,
        required: true
      },
      gender: {
        type: String,
        required: true,
        "enum": ['male', 'female']
      },
      fbPictureUrl: {
        type: String,
        required: true,
        unique: true
      },
      fbLocationId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Location'
      },
      matchingUserIds: {
        type: [
          mongoose.Schema.Types.ObjectId, {
            ref: 'User'
          }
        ]
      }
    });

    return User;

  })();

  module.exports = mongoose.model('User', userSchema);

}).call(this);

//# sourceMappingURL=user.map
