// Generated by CoffeeScript 1.7.1
(function() {
  var AppConfig, ExpressConfig, MongooseConfig, PassportConfig, WebappRouter;

  ExpressConfig = require('./express-config');

  MongooseConfig = require('./mongoose-config');

  PassportConfig = require('./passport-config');

  WebappRouter = require('../src/router');

  AppConfig = (function() {
    var expressConfig, mongooseConfig, passportConfig, webappRouter;

    function AppConfig() {}

    expressConfig = new ExpressConfig();

    mongooseConfig = new MongooseConfig();

    passportConfig = new PassportConfig();

    webappRouter = new WebappRouter();

    AppConfig.prototype.configure = function() {
      var ENV, app;
      ENV = process.env.ENV;
      app = expressConfig.configure(ENV);
      passportConfig.configure(app);
      mongooseConfig.configure();
      webappRouter.setUpRoutes(app);
      return app;
    };

    return AppConfig;

  })();

  module.exports = AppConfig;

}).call(this);

//# sourceMappingURL=app-config.map
