// Generated by CoffeeScript 1.7.1
(function() {
  var ExpressConfig, crypto, env, express, path, stylus;

  crypto = require('crypto');

  express = require('express');

  path = require('path');

  stylus = require('stylus');

  env = require('../env');

  ExpressConfig = (function() {
    function ExpressConfig() {}

    ExpressConfig.prototype.configure = function(ENV) {
      var APP_ROOT, app;
      APP_ROOT = path.join(__dirname, '../');
      app = express();
      app.set('port', env.port);
      app.set('views', APP_ROOT);
      app.set('view engine', 'jade');
      app.use(express.favicon());
      app.use(express.logger('dev'));
      app.use(express.json());
      app.use(express.urlencoded());
      app.use(express.methodOverride());
      app.use(express.cookieParser(crypto.randomBytes(20).toString('hex')));
      app.use(express.session());
      app.use(express["static"](APP_ROOT + 'assets'));
      app.use(stylus.middleware(APP_ROOT + 'assets/styles'));
      app.configure('development', function() {
        app.use(express.errorHandler());
        return app.locals.pretty = true;
      });
      return app;
    };

    return ExpressConfig;

  })();

  module.exports = ExpressConfig;

}).call(this);

//# sourceMappingURL=express-config.map
