// Generated by CoffeeScript 1.7.1
(function() {
  var PageController, UserController, WebappRouter, passport;

  passport = require('passport');

  PageController = require('./page-controller');

  UserController = require('./user/user-controller');

  WebappRouter = (function() {
    var pageController, userController;

    function WebappRouter() {}

    pageController = new PageController();

    userController = new UserController();

    WebappRouter.prototype.setUpRoutes = function(app) {
      app.get('/users', userController.findMatchingUsers);
      app.put('/users/:userId', userController.updateUser);
      app["delete"]('/users/me/matches/:userId', userController.rejectMatch);
      app.get('/partials/:name', pageController.getPartial);
      app.get('/auth/facebook', passport.authenticate('facebook'));
      app.get('/auth/facebook/callback', passport.authenticate('facebook', {
        successRedirect: '/',
        failureRedirect: '/fail'
      }));
      app.post('/users/me/session', pageController.signOutUser);
      app.get('/users/me', pageController.getSignedInUser);
      return app.get('/*', pageController.index);
    };

    return WebappRouter;

  })();

  module.exports = WebappRouter;

}).call(this);

//# sourceMappingURL=router.map
